// Package cabe defines types common to all CABE software.
package cabe

import (
	"time"

	"github.com/messier-42/cabe-go/attrset"
)

// Lease represents a CABE Lease, as obtained via a Prograde operation.
type Lease struct {
	// LeaseID is an optional server-issued identifier used for ARIN
	// invalidation cross-referencing. Empty if a key server doesn't provide it.
	LeaseID string

	// LeaseRef is the opaque lease reference generated by a key server which is
	// quoted in CBES envelopes and used for Retrograde key resolution.
	LeaseRef []byte

	// AttributeSet is the parsed CABE Attribute Set if indicated by the Key Server.
	// A Key Server is not required to provide this in a Lease; it is primarily for
	// diagnostic purposes. The zero value indicates no attribute set was
	// reported.
	AttributeSet attrset.Set

	// LKAI is the Lease Key Access Information needed to make use of the Lease.
	LKAI LKAI

	// Expiry is the point in time at which the Lease should no longer be used.
	Expiry time.Time
}

// LKAI represents CABE Lease Key Access Information provided as the result of a
// Prograde or Retrograde operation. Exactly one of NonCaptive or Captive must be
// non-nil.
type LKAI struct {
	// Non-captive Lease Key access information, which includes the raw key image.
	NonCaptive *LKAINonCaptive
	// Captive Lease Key access information, which includes a Lease Key Access
	// Token (LKAT).
	Captive *LKAICaptive
}

// Valid returns true if the LKAI is at least notionally well-formed. It does not do
// deep validation; see [LKAICaptive.Valid] and [LKAINonCaptive.Valid] for details.
func (lkai *LKAI) Valid() bool {
	if lkai.NonCaptive != nil {
		return lkai.Captive == nil && lkai.NonCaptive.Valid()
	} else {
		return lkai.Captive != nil && lkai.Captive.Valid()
	}
}

// LKAINonCaptive represents a Non-Captive Lease Key. The key is provided
// as a CBOR-encoded COSE_Key structure as defined in [RFC 9052]. Callers may decode
// the structure with the COSE library of their choice.
//
// [RFC 9052]: https://www.rfc-editor.org/rfc/rfc9052
type LKAINonCaptive struct {
	// RawCOSEKey is the CBOR serialisation of a COSE_Key structure.
	RawCOSEKey []byte
}

// Valid returns true if the LKAINonCaptive structure is (potentially) well-formed.
// It does not attempt to deserialize RawCOSEKey or validate that it contains a
// valid COSE_Key; this method is intended for fast rejection of notionally invalid
// values only.
func (l *LKAINonCaptive) Valid() bool {
	return len(l.RawCOSEKey) > 0
}

// LKAICaptive represents a Captive Lease Key's Access Information. Specifically,
// it provides a Lease Key Access Token (LKAT) for use with the AssistedEncapsulate
// and AssistedDecapsulate CKAP protocol operations.
type LKAICaptive struct {
	// The opaque Lease Key Access Token to be quoted back to a Key Server
	// to perform assisted operations.
	LKAT []byte
}

// Valid returns true iff the LKAICaptive structure is well-formed.
func (l *LKAICaptive) Valid() bool {
	return len(l.LKAT) > 0
}
